<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Factory</name>
   <tag></tag>
   <elementGuidId>18932157-89b2-4b11-962b-2e39acb2cce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='masonry']/div/div[2]/div/div[2]/div/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Factory&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2bd4152d-887d-4f03-888e-68d170cbad2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gallery</value>
      <webElementGuid>00f3f85e-98e4-4065-bdb3-6676ab6a038a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Factory</value>
      <webElementGuid>6fad407b-ffb4-4361-bf62-793ef3051c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;masonry&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-md-6 col-sm-6 m-b30&quot;]/div[@class=&quot;dlab-box blog-grid-2&quot;]/div[@class=&quot;dlab-info&quot;]/div[@class=&quot;dlab-post-title&quot;]/h4[@class=&quot;post-title&quot;]/a[1]</value>
      <webElementGuid>f5cb5d25-8b9a-4cf5-aec8-e67a6f6c76c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='masonry']/div/div[2]/div/div[2]/div/h4/a</value>
      <webElementGuid>2ea7e621-b2a6-49e4-88bf-c3a9a01f8b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Factory')]</value>
      <webElementGuid>179f3951-c990-41d0-9e0f-be4961773186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Team'])[1]/following::a[1]</value>
      <webElementGuid>f6b238c3-e2ba-46b9-9e49-9940564953ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo Gallery'])[3]/following::a[2]</value>
      <webElementGuid>e58885eb-2a38-4c49-be35-0844b219c814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gallery'])[1]/preceding::a[1]</value>
      <webElementGuid>80067937-1eaa-4d43-a13a-2a4fae4f1429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gallery'])[2]/preceding::a[2]</value>
      <webElementGuid>58e021cf-3817-4c49-9ffc-a866b7e30f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/gallery')])[11]</value>
      <webElementGuid>5b5e79f1-68d9-4fb9-a33f-caa14d423719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/h4/a</value>
      <webElementGuid>bce4964c-c46b-4aeb-bf61-a63eac88b208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gallery' and (text() = 'Factory' or . = 'Factory')]</value>
      <webElementGuid>976205c6-49e0-4c5a-922a-3d1f39a13d14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
