<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Prev</name>
   <tag></tag>
   <elementGuidId>b5b5e185-4187-4971-9ea0-2dcc56bde2fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.previous > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/div[2]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Prev&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3b20d8a3-02d7-45f7-ba00-87d444213d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gallery</value>
      <webElementGuid>de2da862-3423-47c7-a5e8-d018a1a0eafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Prev</value>
      <webElementGuid>6660ef78-f342-4a65-be40-f8b75603c58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;page-wraper&quot;]/div[@class=&quot;page-content bg-white&quot;]/div[@class=&quot;content-area&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;pagination-bx clearfix  col-md-12 text-center&quot;]/ul[@class=&quot;pagination&quot;]/li[@class=&quot;previous&quot;]/a[1]</value>
      <webElementGuid>597a2856-9418-4382-911f-8e44e817fd58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div[2]/ul/li/a</value>
      <webElementGuid>280fab1c-0b93-4e78-8544-5bd957e947a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Prev')]</value>
      <webElementGuid>46b912ea-b93e-4d79-a158-7d6985f93845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gallery'])[4]/following::a[1]</value>
      <webElementGuid>9f2430a1-c9ce-4d10-a468-67e0958b9854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gallery'])[3]/following::a[2]</value>
      <webElementGuid>529028ad-cde2-4e59-a7f0-0f472869bdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::a[3]</value>
      <webElementGuid>2134be50-490b-4303-b3ff-e3642b062ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News &amp; Articles'])[1]/preceding::a[4]</value>
      <webElementGuid>35cec7b5-18d5-460d-992f-3002849af27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/gallery')])[16]</value>
      <webElementGuid>7e3d3ee6-4a7e-4dc6-833c-21bfd327ee45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/ul/li/a</value>
      <webElementGuid>f3bcb9d1-a28e-48ab-9e65-fb46a861336f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gallery' and (text() = ' Prev' or . = ' Prev')]</value>
      <webElementGuid>e0522545-f86b-4efe-9de7-f5d77e4148f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
