<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LOGINEnter your Username and Password U_562878</name>
   <tag></tag>
   <elementGuidId>470f96b0-ff22-4bec-8f78-bf19bee789d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.auth-bg-video</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.auth-bg-video</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8b5781ea-178e-497f-ac38-eef28ff7434b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth-bg-video</value>
      <webElementGuid>bc2c737b-b5ef-4098-9cdf-270a83d81c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGINEnter your Username and Password User NamePasswordLogin</value>
      <webElementGuid>fa578f68-1e2c-4fcd-b3b0-29c3f231dd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;auth-bg-video&quot;]</value>
      <webElementGuid>1fae0b56-c4c6-4877-b69a-512aa3628830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div</value>
      <webElementGuid>7a42d609-96c4-4b3e-8f72-d1dad04f9788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>7735d4c8-a72e-4a20-9ff9-3640be788d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LOGINEnter your Username and Password User NamePasswordLogin' or . = 'LOGINEnter your Username and Password User NamePasswordLogin')]</value>
      <webElementGuid>909b76a1-a86c-4be2-9518-69838ba8f21c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
