<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload CV_cv</name>
   <tag></tag>
   <elementGuidId>06ce3fb9-44cd-44aa-9732-8d932e9a0e5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exampleFormControlFile2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exampleFormControlFile2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#exampleFormControlFile2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d25f2b0f-a7ba-4338-9b19-3643707c4af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>0c5914e6-cf23-47fb-9c86-f7f522a297f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-file</value>
      <webElementGuid>e1e5ad43-0557-42ff-83c2-e44c27f0b055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleFormControlFile2</value>
      <webElementGuid>96a70d9f-73b8-4d6c-a5b7-d7f7241c5a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cv</value>
      <webElementGuid>af257f53-f8f1-437e-9ebe-76b5946a41ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exampleFormControlFile2&quot;)</value>
      <webElementGuid>04edf26b-965b-4bf2-b3ff-2d89a2bbbe48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exampleFormControlFile2']</value>
      <webElementGuid>f9765480-91e5-456e-bd4c-1c04c502ae4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/div[4]/div[2]/input</value>
      <webElementGuid>a4dd7d92-3183-4e96-b9c9-d85c6ace6e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>a1e46dc8-d87a-4707-8e9d-17859d059ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'exampleFormControlFile2' and @name = 'cv']</value>
      <webElementGuid>10efd574-8398-4871-b391-3ba9b846b08f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
